FROM golang:1.20-alpine

WORKDIR /bot
#ENV TELEGRAM_APITOKEN=!BotFather-tkn!
#ENV SERVER_ADDR=localhost:50051

COPY bot.go ./
COPY client ./client
COPY proto ./proto
COPY go.mod ./

RUN go mod download
RUN go mod tidy

RUN go build -o /tg-bot

CMD [ "/tg-bot" ]
